services:
  - type: web
    name: water-meter-detection
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    healthCheckPath: "/"
    healthCheckInterval: 30
    healthCheckTimeout: 5
    healthCheckRetries: 3
    ports:
      - port: 8000
    routes:
      - src: /api/*
        dest: /api
